name: La Belle Media
favicon: null
layout_spectrum: 0.4318907796405256
typography_spectrum: 0.004701201803982258
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8545495343860239
  lightness: 0.3207719838246703
  saturation: 0.7229463898111135
  rhythmicContrast: 0.8076463222969323
purpose: []
