name: La Belle Media
favicon: null
layout_spectrum: 0.9526
typography_spectrum: 0.004701201803982258
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#000000'
    - '#0cc6ff'
    - '#d07477'
    - '#e42125'
  brandStrength: 0.9375
  lightness: 0.3207719838246703
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
